### PR TITLE
SNMP Set IPAddress support added

### PR DESCRIPTION
**Pull request by MrSpock**
Hi,

My another pull request for support SNMP Set IPAddress type that I added in my fork.
It is very similar to my previous OctetString patch.
You can pass IPAddress into SNMP PDU as string ("10.0.0.1") or []bytes.
If you need pcap files (Sonia asked last time :)) - just let me know - I can provide them for NET SNMP snmpset binary and another one for code above to compare that they are the same.

### CODE REVIEW

**Comment by soniah** [comment]
Thanks MrSpock, the pcap file would be great.

**Comment by soniah** [comment]
Hi @MrSpock I've cherry picked this code into the traps code I'm working on. So it's not in *master* yet, you can find it in *tr1* branch. No sha1 because I'm rebasing all the time :-)

I'll write tests when *.pcap* comes in.

**Comment by MrSpock** [comment]
Hi Sonia,
I'll will send them when I get back from small holidays :)

Pozdr/Kind Regards

Dnia 20.08.2016 o godz. 11:23 Sonia Hamilton <notifications@github.com> napisał(a):

**Comment by MrSpock** [comment]
Do you need single SNMP set for IPAddr inside pcap file ?

**Comment by soniah** [comment]
Two or three ip addresses would be nice, but one will be sufficient. Would you mind rebasing you pull request against HEAD? http://jeffkreeftmeijer.com/2010/the-magical-and-not-harmful-rebase/ gives instructions if you're not sure.

Pozdr/Kind Regards

**Comment by MrSpock** [comment]
It seems that my code is already in master. I made rebase to sync with your master and now when making pull request I'm getting info that there is no difference :)
I pull URL for pcap in next msg.

**Comment by soniah** [comment]
Hi Mr Spock, the github interface is confusing - do you really want to merge 27 billion commits? :-)

I think the best way to handle this would be to do a manual diff between the two branches (yours and master), and do a pull request for any differences. I could do this, but you probably want to get authorship.

The way I do this is have two version of the repo (my main one and another in /var/tmp). Check out one to master and the other to you branch, use tools like meld to investigate.

Bardzo ci dziękuje za pomoc :-)

**Comment by soniah** [comment]
Sweeeet!

**Comment by MrSpock** [comment]
HI, 
Sorry for so long time. Lot of work :/
Didn't found a way to attach file here, so here is link for pcap file for testing.
https://dl.dropboxusercontent.com/u/7660386/go-ipaddress-set.pcap

**Comment by MrSpock** [comment]
Found one code diff between your master and my fork. I don't want to make pull request for single line :)
In gosnmp.go line 293:
	case Integer, OctetString:
should be
	case Integer, OctetString, IPAddress:

**Comment by soniah** [comment]
Thanks @MrSpock . Like you I've been busy ;-) I'll have a look

**Comment by wdreeveii** [comment]
MrSpock,

Too much water under the bridge for this pull request. I am going to close this. 
But please, let me encourage you to resubmit a pull request with your changes against the current master.

Thanks

**Pull request closed without merging**
