### PR TITLE
Add mock for Handler interface

### PR DESCRIPTION
**Pull request by IvanRadakovic**
Hey Soniah,

I added a mock for the Handler interface and left the mockgen comment to update the mock when the interface changes in the future.
Also, I know you just released a new version earlier today, but could you please release another one with the mocks included?

Thank you,
Ivan

### CODE REVIEW

**Comment by soniah** [comment]
Hmmm, I'm trying to understand why I would commit this...

Should it be in .travis.yml? It's not a part of the gosnmp library. And the file is auto-gen'd - why include it?

Long day, I'll have a think about this later in the week :-)

**Comment by IvanRadakovic** [comment]
The motivation behind this is to allow every client to use mocks without requiring them to generate their own mocks in order to use them. This would help anyone using the library to stub out the functions with the mocks.

**Comment by nemith** [comment]
Installing it in travis won't add them for others to use.

**Comment by soniah** [comment]
Merged without travis stuff. Thanks!

**Comment by IvanRadakovic** [comment]
The Travis stuff was so the build would succeed. When I did not include it, the build failed.

**Comment by soniah** [comment]
Build is showing as passing.

https://travis-ci.org/soniah/gosnmp/builds/408393593

**Comment by IvanRadakovic** [comment]
Ok wonderful! When do you plan on releasing another version that includes the mocks?

**Comment by soniah** [comment]
Done :-)

**Pull request closed without merging**
