### PR TITLE
added lots of debug messages in debug mode

### PR DESCRIPTION
**Pull request by toni-moreno**
First approach to a more powerful debug  message system in gosnmp

### CODE REVIEW

**Comment by soniah** [comment]
👍🏼

**Comment by toni-moreno** [comment]
@soniah rebase done!

**Comment by soniah** [comment]
Toni the Travis test has failed. I haven't had time to look yet as I'm travelling for work, would you mind looking?

Thank you for your work!

**Comment by wdreeveii** [comment]
🖒

**Comment by toni-moreno** [comment]
Ok! I'll review ASAP

**Comment by toni-moreno** [comment]
hi @soniah I've finally fixed a mistake in the code. And now all checks are ok!

**Comment by soniah** [comment]
Thanks.

**Comment by soniah** [comment]
Thanks @toni-moreno !! I've squashed your commits into one and fixed up the authorship of your lines. 

Can I close any other issues because of this? eg https://github.com/soniah/gosnmp/issues/109

**Pull request closed without merging**
