### PR TITLE
Fix race issues with global logging vars

### PR DESCRIPTION
**Pull request by rjammala**
Can somebody please review this pull request?

Thanks,
Raj

### CODE REVIEW

**Comment by soniah** [comment]
+1

**Comment by virtuallynathan** [comment]
Seems fine to me, fixes my quick hack.

**Comment by rjammala** [comment]
Thanks for the review(s). Can someone please merge it?

**Comment by wdreeveii** [comment]
At first glance it looks great, but I would like to make a more thorough
review this evening. Unless somebody else wants to do the merge, that is.

On Tue, Jan 12, 2016 at 1:50 PM, Rajanikanth Jammalamadaka <
notifications@github.com> wrote:

> Thanks for the review(s). Can someone please merge it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soniah/gosnmp/pull/59#issuecomment-171087445>.
>



-- 
Whitham D. Reeve II
907-764-5263

**Comment by soniah** [comment]
I too would like to have a better look, run the tests, update the doco and examples, before merging.

**Comment by rjammala** [comment]
Thanks!

**Comment by soniah** [comment]
Merged and other tidying done.

**Pull request closed without merging**
