### PR TITLE
Sha2

### PR DESCRIPTION
**Pull request by StefanHauth**
Rebased branch to master after merge of #230.

### CODE REVIEW

**Comment by soniah** [comment]
Thanks @StefanHauth 🌟 

I've put your PR on branch [pr231](https://github.com/soniah/gosnmp/tree/pr231) (which is just your branch with the linting removed). But there's [lots of failures on Travis](https://travis-ci.org/github/soniah/gosnmp/jobs/678929131), starting from `TestSendV3TrapMD5AuthNoPriv` onwards. Any ideas?

```
=== RUN   TestSendV3TrapMD5AuthNoPriv
--- FAIL: TestSendV3TrapMD5AuthNoPriv (2.02s)
    trap_test.go:542: timed out waiting for trap to be received
=== RUN   TestSendV3TrapSHAAuthNoPriv
--- FAIL: TestSendV3TrapSHAAuthNoPriv (2.02s)
    trap_test.go:635: timed out waiting for trap to be received
=== RUN   TestSendV3TrapSHAAuthDESPriv
--- FAIL: TestSendV3TrapSHAAuthDESPriv (2.00s)
    trap_test.go:731: timed out waiting for trap to be received
=== RUN   TestSendV3TrapSHAAuthAESPriv
--- FAIL: TestSendV3TrapSHAAuthAESPriv (2.02s)
    trap_test.go:828: timed out waiting for trap to be received
=== RUN   TestSendV3TrapSHAAuthAES192Priv
--- FAIL: TestSendV3TrapSHAAuthAES192Priv (2.02s)
    trap_test.go:925: timed out waiting for trap to be received
=== RUN   TestSendV3TrapSHAAuthAES192CPriv
--- FAIL: TestSendV3TrapSHAAuthAES192CPriv (2.00s)
    trap_test.go:1021: timed out waiting for trap to be received
=== RUN   TestSendV3TrapSHAAuthAES256Priv
--- FAIL: TestSendV3TrapSHAAuthAES256Priv (2.00s)
    trap_test.go:1116: timed out waiting for trap to be received
=== RUN   TestSendV3TrapSHAAuthAES256CPriv
--- FAIL: TestSendV3TrapSHAAuthAES256CPriv (2.00s)
    trap_test.go:1212: timed out waiting for trap to be received
```

**Comment by StefanHauth** [comment]
Not from the top of my head. I will have a look.

**Comment by kauppine** [comment]
I did some testing and the issue seems to be with receiving the traps. 
I created a traplistener and tried to send traps to it using NET-SNMP.
https://gist.github.com/kauppine/a49f36fc8a5c64a1b79c8b60b79e74ca
I used this command to send the trap:
```
snmptrap -v3 -e 00abcdefabcdef00  -l authPriv -u user -a SHA -A password -x AES -X password udp:localhost:9162 "" .1.3.6.1.6.3.1.1.5.3.0 0 s "This is a test linkDown trap from v3 authPriv" 
```
And got this output:
```
./trapserver_v3
Packet sanity verified, we got all the bytes (214)
Parsed version 3
Parsed message ID 1194350849
Parsed message max size 65507
parsed msg flags 
Parsed security model 3
Parsed authoritativeEngineID ������
Parsed authoritativeEngineBoots 0
Parsed authoritativeEngineTime 0
Parsed userName user
Parsed authenticationParameters ˠd�g���|
�
Parsed privacyParameters @������
Parsed Security Parameters. now offset=75,
UnmarshalV3Header done. [with SecurityParameters]. Header Size 69. Last 4 Bytes=[[204 250 231 135]]
UnmarshalTrap v3 auth: Incoming packet is not authentic, discarding
```

**Comment by soniah** [comment]
Thanks @StefanHauth I'll have a look 👍

**Comment by StefanHauth** [comment]
I checked the trap receiving code. One problem was that the security keys have not been generated when a trap was received. The other problem was that the tests used different engine IDs for trap sender and trap receiver. I'm not sure if this was done intentionally, but IMHO that can't work as the engine ID is used for the key generation.

**Comment by soniah** [comment]
Thanks @StefanHauth 👍 

I've merged your stuff into https://github.com/soniah/gosnmp/tree/pr231b but there's some other tests failing 😦 https://travis-ci.org/github/soniah/gosnmp/jobs/681375023

 I'll have to investigate them, might just be a matter of increasing the test timeout.

**Comment by StefanHauth** [comment]
For the TestSnmpV3AuthSHA512PrivAES192Get: I think that there's still something not working quite as at it should with the Blumenthal encryption. Running these tests against demo.snmplabs.com doesn't work as well. Using the Reeder encryption (AES192C) it works fine.

However, I think that this isn't related to the main purpose of this branch - getting the authentication for SHA2 working.

If you are not in a hurry, I would volunteer to have a look into the troubles with Blumenthal stuff.

**Comment by soniah** [comment]
If you would like to have a go at *TestSnmpV3AuthSHA512PrivAES192Get*, that
would be great!

The thing that's got me worried is that TestGenericBulkWalk is also failing
<https://travis-ci.org/github/soniah/gosnmp/jobs/681387980>, which means
some underlying logic has changed. I might have to get out the debugger
over the weekend, work out what's changed in that logic from a previously
working commit.

**Comment by StefanHauth** [comment]
What kind of SNMP device (simulation) is used to run the tests in Travis?

**Comment by StefanHauth** [comment]
Uups, my bad! I apologize. I accidentally committed a test switch where demo.snmplabs.com is used for the e2e tests. That - unsurprisingly - had quite an impact on the execution time of the bulk walk.

**Comment by soniah** [comment]
Thanks @StefanHauth ! I've merged this. I haven't had time to fully read the code. But it's Monday morning and the start of another work week, and I want to get this in so as not to hold up other PR's 😮

**Pull request merged**
