### PR TITLE
SNMPv3 integration

### PR DESCRIPTION
**Pull request by soniah**
Squashed commits into one commit, and rebased against master. So we've got a common base to refer to.

### CODE REVIEW

**Comment by soniah** [comment]
See also comments in https://github.com/soniah/gosnmp/pull/50.

**Comment by soniah** [comment]
@wdreeveii Whit I haven't done much this weekend sorry. The Sydney Mardi Gras [1] has been running all weekend in my suburb (like 50 meters away), so, well...

But I've updated the readme on master to say we've got SNMPv3 available, added you as an author :-)

[1] http://www.abc.net.au/news/2015-03-07/mardis-gras-2015-hits-sydney/6288522

**Comment by soniah** [comment]
Hi @wdreeveii Whit thanks again for all your work, it's really great!! Let's get it integrated in to master.

I'm going through our emails, working out how to start on the integration. A few questions:

* would you be able to details the steps (or even write a shell script) for setting up localhost on Ubuntu/Debian/etc for snmpv3? I'm going to need this for the travis integration (travis starts up a blank Ubuntu host, installs packages, then runs the tests), but first I'll start on my desktop. In previous emails you commented:

```
Does this work for you?
snmpwalk -v 3 -u authPrivUser -l authPriv -A testingpass9876543210 -x \
DES -X testingpass9876543210 gosnmp-test-host .1.3.6.1.2.1.1.1.0
```
and
```
For reference, I have included below the users/passwords necessary \
for tests against 'gosnmp-test-host' to work (net-snmp snmpd).

createUser noAuthNoPrivUser
createUser authOnlyUser MD5 testingpass0123456789
createUser authOnlyUsersha SHA testingpass9876543210
createUser authPrivUser MD5 testingpass9876543210 DES

rouser noAuthNoPrivUser noauth
rouser authOnlyUser auth
rouser authOnlyUsersha auth
rouser authPrivUser authPriv
```
So I want to setup up localhost with the above settings.

* I remember you telling me why `TestUnmarshal` in `marshal_test.go` was disabled - what was the reason again? I want to get that test going again.

**Comment by soniah** [comment]
Copying across @codedance 's comments, so we don't have to flick between branches:

This is quite a big delta.  It might also be worth taking the opportunity to look some refactoring. Some of the files are getting quite big.  I'll also dive in and take a more detailed look.  I've got a 12 hour plane flight to the coming up this weekend so this might pass the time :-)

Just a few thoughts from my 5 minute scan:

* The random is used for hmac salts, etc.  The Rand implementation should be changed to `crypto/rand` to guarantee entropy.  (History: `math/rand` was first added simply as a way to seed the incrementing request ID on startup to minimise chance of collisions if an application was quickly restarted)  

* Reactor: Maybe we should consider move the logic into the security.go file - it will slim down some of the density on the main files and also provide a bit of an indication to developers that you should think along these lines when playing around.  e.g. hmac*(), guts of authenticate()

* Need some comments - at least function level.

* SNMPv3 it about security.  It would be good to do a careful walk-through on the code in this respect.  Many eyes would be good :-)

Great work btw!

**Comment by wdreeveii** [comment]
Sorry for the delay folks, I took a badly needed break from the computer over the weekend. My employer recently acquired 120k new wireless subscribers so it has been very busy at the office.

Please find the shell script used to install test users in this gist https://gist.github.com/wdreeveii/63ec71f38a9c1ace2d91

The use configuration can be tested with (for example) the following:
snmpwalk -v3 -u authMD5PrivDESUser -l authPriv -a MD5 -A testingpass9876543210 -x DES -X testingpass9876543210 localhost .1.3.6.1.2.1.1.1.0

I cleaned up the usernames that were created rather organically, so the snmpwalk you provided will not work.
##################

TestUnmarshal had to be disabled because it needs access to a copy of a UsmSecurityParameters to properly decode a packet. The easiest way to do that is to make unmarshal a member of the base GoSNMP structure. This has complicated testing because now you need to mock the GoSNMP struct... I just disabled it to (temporarily) avoid the frustration.

I did a little investigation and the SnmpPacket struct contains a copy of UsmSecurityParameters but it is initalized to a zero value inside unmarshal. If we wanted to modify the api a little bit, unmarshal could take an initialized SnmpPacket aswell as the packet bytes to get rid of the connection with GoSNMP.

**Comment by wdreeveii** [comment]
Hey folks, I made some progress on implementing the requested changes. 

First, I reenabled TestUnmarshal by removing the coupling between unmarshal and GoSNMP. The code now passes in a SnmpPacket for unmarshal to fill in, and that packet contains a copy of the SecurityParameters.

Second, I implemented the crypto/rand implementation for AES/DES salts. Interesting that they do not use the same API - it was not a drop in replacement, and for that reason the RequestID/MsgID use the existing math/rand implementation. The RFCs do not suggest that RequestIDs/MsgIDs should be especially random so I am fairly comfortable with this.

Third, I moved some of the security related code into security.go and added some comments as requested.

**Comment by ctrlrsf** [comment]
Hi @wdreeveii,

I looked over these additional 5 commits and they look sane to me.

**Comment by soniah** [comment]
:+1:

**Comment by wdreeveii** [comment]
I just pushed a commit to start verifying the authenticity of incoming packets. 

After the unmarshal function parses the authentication parameters, it rewrites the 12 octet authentication parameter in the packet to 0s and runs the same hmac algorithm on the packet bytes that is used to authenticate outgoing packets.

The HMAC signing process depends on the authentication parameter, the authentication protocol, the authentication passphrase, and the authoritative engine ID.

It extracts the authentication parameter from the incoming message and compares it against the already established authentication protocol/authentication passphrase/authoritative engine ID.

If the HMAC digests obtained from the incoming message, and the one computed from the previously established parameters, it bombs out with an error.

Keep in mind that I haven't tested an agent that provides an incorrect digest to confirm that it bombs out properly, but the code feels correct. Needless to say I would like to write a test to confirm that, but ahhhhhhhhhhhhhhhhhhhhhhhhhhhh...

**Comment by wdreeveii** [comment]
I think that concludes the modifications I have been wanting to make. Are there any other requests out there?

**Pull request closed without merging**
