### PR TITLE
Sha2

### PR DESCRIPTION
**Pull request by StefanHauth**
Implementation of RFC7860
* support of new SHA2 hashes
* more E2E tests to cover scenarios
* possibility to use demo.snmplabs.com out-of-the-box for tests, no need for complicated local SNMP agent setup, supports most recent authentication and privacy features for SNMP v3

I've also rebased the branch to the current master and did some small refactorings where necessary.

### CODE REVIEW

**Comment by soniah** [comment]
Thanks @StefanHauth this is really great. I've just merged a different large [PR](https://github.com/soniah/gosnmp/pull/224). Would you mind rebasing yours and checking all is good? Thanks, Sonia.

**Comment by hauti123** [comment]
Sure, no problem!

Am Mi., 15. Apr. 2020 um 09:45 Uhr schrieb Sonia Hamilton <
notifications@github.com>:

**Comment by soniah** [comment]
Thanks https://github.com/kauppine for your message on the https://github.com/soniah/gosnmp/pull/224 thread.

I think it would be better to rebase https://github.com/soniah/gosnmp/pull/225 against current HEAD of master, just to make sure everything is ok. It'll only take a day or two longer :-)

**Comment by StefanHauth** [comment]
I've removed my last commit where I reverted the fix of @kauppine

**Comment by kauppine** [comment]
@StefanHauth thanks for noticing that my PR broke those tests. I've fixed the issue and issued a new PR: #227

**Pull request merged**
